name: fatfrogkingdom
services:
- name: web
  github:
    branch: main
    deploy_on_push: true
  build_command: npm install && npm run build
  run_command: npm run start
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  env:
    - key: NODE_ENV
      value: production
    - key: PORT
      value: "8080"
    - key: NEXT_PUBLIC_CLIENT_ID
      value: "149584c7b4535aef52db119d20cbd442"
    - key: NEXT_PUBLIC_NFT_CONTRACT_ADDRESS
      value: "0xE4637e7425A2d19c4f7A23A36a1f5f844872e6c5"
    - key: NEXT_PUBLIC_STAKING_CONTRACT_ADDRESS
      value: "0x6A39b9404606e82a70bFb281f36737C018C1335F"
    - key: NEXT_PUBLIC_REWARD_TOKEN_CONTRACT_ADDRESS
      value: "0xf9b864b6d7B2f6348f6adDE5557c676f14FB53e8"
  http_port: 8080
  health_check:
    http_path: /api/health
    initial_delay_seconds: 10
    period_seconds: 10
    timeout_seconds: 5
    success_threshold: 1
    failure_threshold: 3
