name: fatfrogkingdom
services:
- name: web
  github:
    branch: main
    deploy_on_push: true
  build_command: npm install && npm run build
  run_command: npm start
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  env:
    - key: NODE_ENV
      value: production
    - key: PORT
      value: "8080"
    - key: NEXT_TELEMETRY_DISABLED
      value: "1"
  routes:
    - path: /.*
      preserve_path_prefix: true
  source_dir: /
